version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agtools-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    command: uvicorn main:app --host=0.0.0.0 --port=8000 --reload 
    volumes:
      - ./:/usr/src

  db:
    image: postgis/postgis:15-3.4-alpine
    container_name: geolocations-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: